### ISSUE TITLE
Capstone prep tracking issue

### ISSUE THREAD

**Issue by dymurray** [konveyor/oadp-capstone#3]
## Step 1
- [ ] Remove non-OLM instructions
- [ ] Remove secret creation step (not required when `noobaa: true` is set)
- [ ] Need to publish OLM metadata to Konveyor org instead of Devarsh's. User should just have to create the operator-source file

## Step 4
- [ ] Update for OLM install from web UI (Create `Velero` CR directly from console)
- [ ] Will need to edit the CR's spec to set `noobaa: true` and remove BSL info
- [ ] Screenshot of pods running in cluster from web UI? (optional)
- [ ] Debugging instructions for Noobaa+Operator (can link to external document if desired)

## Step 6
- [ ] Discuss what hooks are doing behind the scenes, remove explicit instructions to annotate
- [ ] Use `velero describe backup` to get output on PV backupss as well
- [ ] Include instructions to seed DB with data

## Step 7
- [ ] Screenshot of Noobaa login
- [ ] Screenshot of k8s resources in noobaa bucket
- [ ] Screenshot of internal image stored in s3 bucket (inside of `docker` directory)

## Step 8
- [ ] Delete internal image? (optional)
- [ ] Show PV data deleted? (optional)

## Step 9
- [ ] Show DB data after restore
